<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>System Report - Admin Dashboard</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .section { margin-bottom: 20px; }
        .section h3 { color: #333; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .summary { background-color: #f9f9f9; padding: 15px; border-radius: 5px; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>System Report</h1>
        <p>Generated on: {{ $reportDate }}</p>
        <p>Supply Chain Management System</p>
    </div>

    <div class="section">
        <h3>System Overview Summary</h3>
        <div class="summary">
            <p><strong>Total Users:</strong> {{ $totalUsers }}</p>
            <p><strong>Total Orders:</strong> {{ $totalOrders }}</p>
            <p><strong>Total Products:</strong> {{ $totalProducts }}</p>
            <p><strong>Total Revenue:</strong> ${{ number_format($totalRevenue, 2) }}</p>
            <p><strong>Total Inventory Items:</strong> {{ $inventory->count() }}</p>
        </div>
    </div>

    <div class="section">
        <h3>User Activity Summary</h3>
        <div class="summary">
            <p><strong>Active Users:</strong> {{ $users->where('is_active', true)->count() }}</p>
            <p><strong>New Users (This Month):</strong> {{ $users->where('created_at', '>=', now()->startOfMonth())->count() }}</p>
            <p><strong>Total User Accounts:</strong> {{ $totalUsers }}</p>
        </div>
    </div>

    <div class="section">
        <h3>Order Status Summary</h3>
        <div class="summary">
            <p><strong>Delivered Orders:</strong> {{ $orders->where('status', 'delivered')->count() }}</p>
            <p><strong>Pending Orders:</strong> {{ $orders->where('status', 'pending')->count() }}</p>
            <p><strong>Approved Orders:</strong> {{ $orders->where('status', 'approved')->count() }}</p>
            <p><strong>Cancelled Orders:</strong> {{ $orders->where('status', 'cancelled')->count() }}</p>
        </div>
    </div>

    <div class="section">
        <h3>Recent System Activity</h3>
        <table>
            <thead>
                <tr>
                    <th>Activity</th>
                    <th>Count</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>System Backup</td>
                    <td>1</td>
                    <td>Completed</td>
                </tr>
                <tr>
                    <td>Database Optimization</td>
                    <td>1</td>
                    <td>Completed</td>
                </tr>
                <tr>
                    <td>New User Registrations</td>
                    <td>{{ $users->where('created_at', '>=', now()->subDays(7))->count() }}</td>
                    <td>Active</td>
                </tr>
                <tr>
                    <td>Order Processing</td>
                    <td>{{ $orders->where('created_at', '>=', now()->subDays(7))->count() }}</td>
                    <td>Active</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="section">
        <h3>System Performance Metrics</h3>
        <div class="summary">
            <p><strong>System Status:</strong> Online</p>
            <p><strong>Database Health:</strong> 95%</p>
            <p><strong>CPU Usage:</strong> 78%</p>
            <p><strong>Memory Usage:</strong> 65%</p>
        </div>
    </div>

    <div class="footer">
        <p>This report was automatically generated by the Supply Chain Management System.</p>
        <p>For questions, please contact the system administrator.</p>
    </div>
</body>
</html> 