<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Retailer Report - {{ $retailer->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .section { margin-bottom: 20px; }
        .section h3 { color: #333; border-bottom: 1px solid #ccc; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .summary { background-color: #f9f9f9; padding: 15px; border-radius: 5px; }
        .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Retailer Daily Report</h1>
        <p>Generated on: {{ $reportDate }}</p>
        <p>Retailer: {{ $retailer->name }}</p>
        <p>Store: {{ $retailStore->name ?? 'N/A' }}</p>
    </div>

    <div class="section">
        <h3>Sales Analytics Summary</h3>
        <div class="summary">
            <p><strong>Total Orders:</strong> {{ $stats['total_orders'] }}</p>
            <p><strong>Monthly Orders:</strong> {{ $stats['monthly_orders'] }}</p>
            <p><strong>Total Cost:</strong> ${{ number_format($stats['total_cost'], 2) }}</p>
            <p><strong>Delivered Orders:</strong> {{ $stats['delivered_orders'] }}</p>
        </div>
    </div>

    <div class="section">
        <h3>Inventory Summary</h3>
        <div class="summary">
            <p><strong>Total Products:</strong> {{ $stats['products_count'] }}</p>
            <p><strong>Low Stock Items:</strong> {{ $stats['low_stock_products'] }}</p>
            <p><strong>Pending Orders:</strong> {{ $stats['pending_orders'] }}</p>
            <p><strong>Approved Orders:</strong> {{ $stats['approved_orders'] }}</p>
        </div>
    </div>

    <div class="section">
        <h3>Order Status Summary</h3>
        <div class="summary">
            <p><strong>Delivered Orders:</strong> {{ $stats['delivered_orders'] }}</p>
            <p><strong>Pending Orders:</strong> {{ $stats['pending_orders'] }}</p>
            <p><strong>Cancelled Orders:</strong> {{ $stats['cancelled_orders'] }}</p>
            <p><strong>Rejected Orders:</strong> {{ $stats['rejected_orders'] }}</p>
        </div>
    </div>

    <div class="section">
        <h3>Recent Orders</h3>
        @if($orders->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Status</th>
                        <th>Amount</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($orders->take(10) as $order)
                        <tr>
                            <td>#{{ $order->id }}</td>
                            <td>{{ ucfirst($order->status) }}</td>
                            <td>${{ number_format($order->total_amount, 2) }}</td>
                            <td>{{ $order->created_at->format('Y-m-d') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No orders found.</p>
        @endif
    </div>

    <div class="section">
        <h3>Inventory Summary</h3>
        @if($inventory->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Location</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($inventory->take(10) as $item)
                        <tr>
                            <td>{{ $item->product->name ?? 'N/A' }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td>{{ $item->location_id ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No inventory records found.</p>
        @endif
    </div>

    <div class="footer">
        <p>This report was automatically generated by the Supply Chain Management System.</p>
        <p>For questions, please contact the system administrator.</p>
    </div>
</body>
</html> 